### ISSUE TITLE
BG coloring

### ISSUE THREAD

**Issue by deeflorian** [jeffmillies/flex-gauge#1]
BG colors cannot be set properly thanks to the light-saturation setting combination.

**Comment by jeffmillies** [comment]
How are you trying to set it and what is the desired result?

**Comment by deeflorian** [comment]
Different FG colors (blue&red) on two different gauges required the same BG color (same color code given by the designer) -- after setting it, the two produced different, quite unrelated colors. I didn't find anything related in the docs, so we played with the light and saturation until it became roughly the same. A simple way for setting an exact color would be nice.

**Comment by jeffmillies** [comment]
If you could provide the color codes used for the FG and BG, I'd be curious to try it out and replicate the issue and fix it. Let me know
